### ISSUE TITLE
The project is very interesting.

### ISSUE THREAD

**Issue by fabric-io-rodrigues** [mg98/filter.js#1]
I was looking for a way to filter objects using SQL/CQL but that only ran on the frontend and I couldn't find it, so I got here. Congratulations on the project.

Do you intend to use some SQL parser? How: [node-sql-parser](https://github.com/taozhi8833998/node-sql-parser) or [js-sql-parser](https://github.com/JavaScriptor/js-sql-parser) to filter using abstract syntax tree (AST).

**Comment by mg98** [comment]
Hey, thank you very much!
To be honest, I wasn't aware of sql parsers in js when I started this, but just really needed something to let my non-tech users have a way to express comprehensive filters. So I built a freestyle solution. It's not yet fully where I want it to be but it's going well. Are there any specific features you're missing?

**Comment by fabric-io-rodrigues** [comment]
Cool, I'll follow your development! I was also looking for a way to filter the data from a table (very similar to the demo) but that ran only on the client side. What I need is to get the project in .js format, to run in local HTML like JQuery/BootStrap. I looked on the CDN but couldn't find it.

**Comment by mg98** [comment]
I see. I'll definitely check this when I find the time!

**Comment by mg98** [comment]
Finally got some time for this. That's what you were talking about, right?
https://github.com/mg98/filter.js#usage-in-browser
